#!/usr/bin/env python3
"""
Social Media Watcher - Gold Tier Skill
Monitors Facebook messages for business-critical keywords and creates action items.
"""

import os
import time
from datetime import datetime
from pathlib import Path
from playwright.sync_api import sync_playwright
from Scripts.retry_handler import with_retry

# Business keywords to monitor
BUSINESS_KEYWORDS = ['client', 'urgent', 'sale', 'project', 'pricing']

# Paths
VAULT_ROOT = Path(__file__).parent
USER_DATA_DIR = VAULT_ROOT / 'user_data' / 'social_session'
NEEDS_ACTION_BUSINESS = VAULT_ROOT / 'Needs_Action' / 'Business'


def setup_directories():
    """Create necessary directories if they don't exist."""
    USER_DATA_DIR.mkdir(parents=True, exist_ok=True)
    NEEDS_ACTION_BUSINESS.mkdir(parents=True, exist_ok=True)


@with_retry(max_attempts=3)
def check_for_business_messages(page):
    """
    Check Facebook messages for business-critical keywords.

    Args:
        page: Playwright page object

    Returns:
        list: List of message dictionaries containing sender, text, and timestamp
    """
    business_messages = []

    try:
        # Wait for messages to load
        page.wait_for_selector('[role="main"]', timeout=10000)

        # Get unread message threads (this selector may need adjustment based on Facebook's UI)
        unread_threads = page.query_selector_all('[aria-label*="unread"]')

        for thread in unread_threads[:5]:  # Check first 5 unread threads
            try:
                # Click on the thread to open it
                thread.click()
                time.sleep(2)  # Wait for messages to load

                # Get the sender name
                sender_element = page.query_selector('[role="heading"]')
                sender = sender_element.inner_text() if sender_element else "Unknown Sender"

                # Get recent messages in the thread
                message_elements = page.query_selector_all('[role="row"]')

                for msg_element in message_elements[-3:]:  # Check last 3 messages
                    message_text = msg_element.inner_text()

                    # Check if message contains business keywords
                    if any(keyword.lower() in message_text.lower() for keyword in BUSINESS_KEYWORDS):
                        business_messages.append({
                            'platform': 'Facebook',
                            'sender': sender,
                            'text': message_text,
                            'timestamp': datetime.now().isoformat()
                        })

            except Exception as e:
                print(f"Error processing thread: {e}")
                continue

    except Exception as e:
        print(f"Error checking messages: {e}")

    return business_messages


@with_retry(max_attempts=3)
def navigate_to_facebook(page):
    """Navigate to Facebook Messages with retry logic."""
    page.goto('https://www.messenger.com/', timeout=0)


@with_retry(max_attempts=3)
def reload_page(page):
    """Reload page with retry logic."""
    page.reload()


def create_action_item(message_data):
    """
    Create a markdown file in /Needs_Action/Business/ for a business message.

    Args:
        message_data: Dictionary containing message information
    """
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"SOCIAL_MSG_{timestamp}.md"
    filepath = NEEDS_ACTION_BUSINESS / filename

    content = f"""# Social Media Message - Business Alert

**Platform:** {message_data['platform']}
**Sender:** {message_data['sender']}
**Received:** {message_data['timestamp']}

## Message Content

{message_data['text']}

---
*Auto-generated by Social Media Watcher*
"""

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"[SUCCESS] Created action item: {filename}")


def run_watcher():
    """Main watcher loop that monitors Facebook messages."""
    setup_directories()

    print("[WATCHER] Social Media Watcher Starting...")
    print(f"   Monitoring for keywords: {', '.join(BUSINESS_KEYWORDS)}")
    print(f"   Session data: {USER_DATA_DIR}")
    print(f"   Action items: {NEEDS_ACTION_BUSINESS}")
    print("\n[WARNING] FIRST RUN: Please log in to Facebook manually in the browser window.")
    print("   Your session will be saved for future runs.\n")

    with sync_playwright() as p:
        # Launch browser with persistent context
        context = p.chromium.launch_persistent_context(
            user_data_dir=str(USER_DATA_DIR),
            headless=False,  # Set to True after first login
            channel='chrome',
            args=['--disable-blink-features=AutomationControlled', '--disable-extensions'],
            ignore_default_args=['--enable-automation']
        )

        page = context.pages[0] if context.pages else context.new_page()

        # Navigate to Facebook Messages
        navigate_to_facebook(page)

        print("[SUCCESS] Browser launched. Waiting for login if needed...\n")
        time.sleep(10)  # Give user time to log in on first run

        # Main monitoring loop
        check_count = 0
        while True:
            try:
                check_count += 1
                print(f"[{datetime.now().strftime('%H:%M:%S')}] Check #{check_count} - Scanning messages...")

                # Refresh the page to get latest messages
                reload_page(page)
                time.sleep(3)

                # Check for business messages
                business_messages = check_for_business_messages(page)

                if business_messages:
                    print(f"   Found {len(business_messages)} business-critical message(s)!")
                    for msg in business_messages:
                        create_action_item(msg)
                else:
                    print("   No new business messages.")

                # Wait 15 seconds before next check
                print(f"   Next check in 15 seconds...\n")
                time.sleep(15)

            except KeyboardInterrupt:
                print("\n\n[STOPPED] Watcher stopped by user.")
                break
            except Exception as e:
                print(f"   Error in monitoring loop: {e}")
                print("   Retrying in 15 seconds...\n")
                time.sleep(15)

        context.close()


if __name__ == '__main__':
    run_watcher()
